[2021-06-27 04:52:20,685] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:52:20,692] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:52:20,692] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:52:20,692] {taskinstance.py:867} INFO - Starting attempt 2 of 2
[2021-06-27 04:52:20,692] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:52:20,701] {taskinstance.py:887} INFO - Executing <Task(BashOperator): csv_file_check> on 2021-06-26T00:00:00+00:00
[2021-06-27 04:52:20,703] {standard_task_runner.py:53} INFO - Started process 1963 to run task
[2021-06-27 04:52:20,751] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 04:52:20,763] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-06-27 04:52:20,765] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp8ELC2k/csv_file_checknTvn5d
[2021-06-27 04:52:20,765] {bash_operator.py:115} INFO - Running command: shasum ~/airflow/datasources/src2/data*
[2021-06-27 04:52:20,770] {bash_operator.py:122} INFO - Output:
[2021-06-27 04:52:20,795] {bash_operator.py:126} INFO - shasum: /home/ubuntu/airflow/datasources/src2/data*:
[2021-06-27 04:52:20,796] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-06-27 04:52:20,803] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2021-06-27 04:52:20,804] {taskinstance.py:1170} INFO - All retries failed; marking task as FAILED.dag_id=csv_data_ingesation, task_id=csv_file_check, execution_date=20210626T000000, start_date=20210627T045220, end_date=20210627T045220
[2021-06-27 04:52:30,683] {logging_mixin.py:112} INFO - [2021-06-27 04:52:30,683] {local_task_job.py:103} INFO - Task exited with return code 1
